### ISSUE TITLE
Cannot cd ${GITHUB_WORKSPACE}

### ISSUE THREAD

**Issue by robandpdx** [cygwin/cygwin-install-action#11]
I'll start by acknowledging that this is probably not an issue with this action. However, anyone that uses this action and intends to use `shell: C:\cygwin\bin\bash.exe -l '{0}'` will likely face this issue. Therefore, solving this issue here would be helpful to the community of uses here.  

[This section of the README](https://github.com/cygwin/cygwin-install-action/?tab=readme-ov-file#path) says to `cd ${GITHUB_WORKSPACE}` in your shell script if you are using a login shell (`bash -l`). It seem so simple, yet I cannot make that work.  

Here is my workflow to demonstrate the issue with `cd ${GITHUB_WORKSPACE}` using a login shell...  
```
name: Cygwin testing
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
  issue_comment:
  workflow_dispatch:
  issues:
    types: 
      - opened

jobs:
  install-cygwin-and-do-stuff:
    runs-on: windows-latest
    steps:
      - run: git config --global core.autocrlf input
      - uses: actions/checkout@v2

      - name: Install cygwin
        uses: cygwin/cygwin-install-action@master
        with:
          packages: >-
            coreutils
            moreutils

      - name: Show cygwin env with login shell
        shell: C:\cygwin\bin\bash.exe -l '{0}'
        env:
          CYGWIN_NOWINPATH: 1
        run: |
          echo "PWD = $(pwd)"
          echo "GITHUB_WORKSPACE = ${GITHUB_WORKSPACE}"
          echo "cygpath GITHUB_WORKSPACE = $(cygpath ${GITHUB_WORKSPACE})"
          echo "cd into GITHUB_WORKSPACE..."
          cd "${GITHUB_WORKSPACE}"
```

I have tried several different things in place of `${GITHUB_WORKSPACE}` in the workflow above with different results, noted below...  
| Attempt | Result |
|---------|--------|
| `cd "$(cygpath ${GITHUB_WORKSPACE})"` | `cd: $'/cygdrive/d/a/tools/tools\r': No such file or directory` |
| `cd /cygdrive/d/` | `cd: $'/cygdrive/d/\r': No such file or directory` |
| `cd "${GITHUB_WORKSPACE}"` | `cd: $'D:\\a\\tools\\tools\r': No such file or directory` |

I appreciate any help with this. Thank you!
