### ISSUE TITLE
unable to use cygwin as shell if add-to-path: false

### ISSUE THREAD

**Issue by jeremyd2019** [cygwin/cygwin-install-action#29]
I tried to do
```yaml
      - id: cygwin
        uses: cygwin/cygwin-install-action@master
        with:
          packages: ...
      - name: build
        run: ...
        shell: ${{ steps.cygwin.outputs.root }}\bin\bash.exe -leo pipefail -o igncr '{0}'
```

but apparently hit https://github.com/actions/runner/issues/444.

What I propose (and can make a PR for if you like) is what setup-msys2 action does: create a directory under `${{ runner.temp }}` with a .cmd script that invokes the correct bash, and adds that to the PATH, so that subsequent steps can use `shell: cygwin.cmd '{0}'`.

**Comment by jon-turney** [comment]
Yes, please make a PR.

I'm not overly-enamored of `add-to-path: false` (which should be in your example above?) meaning "You asked me to leave the path alone, but I changed it anyway...", but I don't see any other way to work-around this other than guessing where we got installed...

**Comment by jeremyd2019** [comment]
It looks like @lazka already pretty well implemented that on that PR mention above ⬆️ just copy/paste that :grin:
The only question is whether it should be using `-l` or `--noprofile --norc`.  I tend to want to set `CHERE_INVOKING` and a login shell, but it seems like `--noprofile --norc` is more common (and then following that up with every step setting the `PATH`)

**Comment by lazka** [comment]
Copying that here for future reference, feel free to ignore:

```yaml
      - name: Create cygwin shell wrapper and add to PATH
        shell: pwsh
        env:
          INSTALL_DIR: ${{ matrix.INSTALL_DIR }}
        run: |
          $wrapperDir = Join-Path $env:RUNNER_TEMP "_cygwin_shell"
          New-Item -Path $wrapperDir -ItemType Directory -Force | Out-Null
          Set-Content -Path (Join-Path $wrapperDir "cygwin.cmd") -Value "@echo off`r`n$env:INSTALL_DIR\\bin\\bash.exe --noprofile --norc -o igncr -eo pipefail %*"
          echo "$wrapperDir" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
```
