### ISSUE TITLE
[feature] Make cygwin-packages dir configurable

### ISSUE THREAD

**Issue by sebthom** [cygwin/cygwin-install-action#7]
Currently it is hardcoded to C:\cygwin-packages

**Comment by sebthom** [comment]
I want to do:

```yaml
jobs:
  build:
    runs-on: windows-latest
    steps:     
    - name: "Cache: Cywgin Repository"
      uses: actions/cache@v3
      with:
        path: "${{ runner.tool_cache }}/cygwin-packages"
        key: ${{ runner.os }}-cygwin-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-cygwin-

    - uses: cygwin/cygwin-install-action@master
       with:
         packages-dir: ${{ runner.tool_cache }}/cygwin-packages
```

Also I don't see why the install dir can be customized but the packages cache dir not.
