### ISSUE TITLE
Invoke-WebRequest to "https://cygwin.com/setup-$platform.exe" failing sporadically

### ISSUE THREAD

**Issue by Edward-Knight** [cygwin/cygwin-install-action#9]
This Action is used in [indygreg/python-build-standalone](https://github.com/indygreg/python-build-standalone/), and I'm seeing some sporadic failures on the line:
```
Invoke-WebRequest https://cygwin.com/setup-$platform.exe -OutFile C:\setup.exe
```
https://github.com/cygwin/cygwin-install-action/blob/006ad0b0946ca6d0a3ea2d4437677fa767392401/action.yml#L45C9-L45C87

Usage here:
```
- name: Install Cygwin Environment
  uses: cygwin/cygwin-install-action@49f298a7ebb00d4b3ddf58000c3e78eff5fbd6b9
  with:
    packages: autoconf automake libtool
```
https://github.com/indygreg/python-build-standalone/blob/85923ca3911784e6978b85d56e06e9ae75cb2dc4/.github/workflows/windows.yml#L61-L64

Failures look like:
```
Invoke-WebRequest https://cygwin.com/setup-$platform.exe -OutFile C:\setup.exe
  shell: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.EXE -command ". '{0}'"
Invoke-WebRequest : The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
```
[example 1](https://github.com/indygreg/python-build-standalone/actions/runs/5321881110/jobs/9637618701#step:19:30), [example 2](https://github.com/indygreg/python-build-standalone/actions/runs/5303346325/jobs/9598919039#step:19:30)

---

This looks like a sporadic network failure, but I'm unclear where exactly the problem is. I'm thinking this could potentially be made reliable with a retry mechanism. Would you be open to a patch that implements this?
